In [4]:
import numpy as np

In [5]:
dists = np.random.rand(100, 5)
dists = (dists.T/np.sum(dists, axis=1)).T

In [6]:
dists

array([[1.64660884e-01, 1.33201311e-01, 1.59669529e-01, 3.76254182e-02,
        5.04842857e-01],
       [3.01523219e-01, 2.86568963e-01, 4.08051169e-03, 1.42174774e-01,
        2.65652532e-01],
       [2.53880745e-02, 2.21791430e-01, 2.86604426e-01, 1.97085498e-01,
        2.69130571e-01],
       [1.91548853e-01, 5.76308864e-02, 3.24482120e-01, 2.43208628e-01,
        1.83129513e-01],
       [3.84953624e-01, 1.17107117e-01, 6.51531955e-02, 3.54032164e-01,
        7.87538992e-02],
       [2.75087502e-01, 1.35989970e-01, 3.67921903e-01, 1.57144799e-01,
        6.38558269e-02],
       [3.44434449e-02, 2.91404615e-01, 3.05314333e-01, 1.25643137e-01,
        2.43194470e-01],
       [2.87158539e-01, 1.56909923e-01, 3.27714731e-01, 1.63062129e-01,
        6.51546790e-02],
       [2.50098905e-01, 9.67027666e-02, 3.63703170e-01, 2.30550797e-01,
        5.89443611e-02],
       [1.49925346e-01, 2.33121199e-01, 9.80112002e-02, 9.35101920e-02,
        4.25432063e-01],
       [1.38129931e-01, 1.1569

In [7]:
def random_neighbors(dists):
    prob_cum = np.cumsum(dists, axis=1)
    r = np.random.rand(dists.shape[0])
    return np.argmax((r < prob_cum.T).T, axis=1)

In [8]:
%%timeit
random_neighbors(dists)

24.7 µs ± 3.83 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [9]:
indices = list(range(5))

In [10]:
%%timeit
np.apply_along_axis(lambda x: np.random.choice(indices, p=x), axis=1, arr=dists)

3.4 ms ± 293 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [11]:
results = []
for _ in range(10000):
    results.append(random_neighbors(dists)[0])

In [12]:
indices, counts = np.unique(results, return_counts=True)

In [13]:
counts/np.sum(counts)

array([0.1698, 0.1314, 0.1561, 0.037 , 0.5057])

In [14]:
dists[0]

array([0.16466088, 0.13320131, 0.15966953, 0.03762542, 0.50484286])

In [15]:
tmp = np.array([[0, 1, 2], [1, 2, 3], [2, 3, 4], [3, 4, 5]])

In [16]:
tmp

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [17]:
tmp[np.array([0, 2, 3]), np.array([0, 1, 0])]

array([0, 3, 3])

In [18]:
def test_function(param0={}, param1=0):
    if param1 == 0:
        param0['a'] = 2
    return param0

print(test_function(param1=0))
print(test_function(param1=1))


{'a': 2}
{'a': 2}


In [19]:
def cartesian_product(*arrays):
    la = len(arrays)
    dtype = np.result_type(*arrays)
    arr = np.empty([len(a) for a in arrays] + [la], dtype=dtype)
    for i, a in enumerate(np.ix_(*arrays)):
        arr[...,i] = a
    return arr.reshape(-1, la)

weights = np.array([[1, 2, 3],
                    [4, 5, 6]]).T
weights = weights / np.sum(weights)

coords = cartesian_product(np.array([0, 1, 2]), np.array([0, 1]))
coords[np.random.choice(np.arange(len(coords)), 20, p=weights[coords[:,0], coords[:,1]])]

In [26]:
weights[coords[:,0], coords[:,1]]

array([0.04761905, 0.19047619, 0.0952381 , 0.23809524, 0.14285714,
       0.28571429])

In [29]:
coords

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1],
       [2, 0],
       [2, 1]])

array([[0, 0],
       [0, 1],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 1],
       [2, 0],
       [2, 1],
       [2, 1],
       [1, 1],
       [1, 1],
       [2, 1],
       [0, 1],
       [1, 1],
       [2, 1],
       [0, 1],
       [1, 1],
       [2, 1]])