In [1]:
import numpy as np
import itertools
from smote_variants import array_array_index, base_idx_neighbor_idx_simplices, all_neighbor_simplices_real_idx, simplex_volume, simplex_volumes
from smote_variants import SimplexSamplingMixin

from sklearn.neighbors import NearestNeighbors

In [2]:
from smote_variants import SMOTE

In [3]:
simplex = np.array([[1, 0, 0],
                    [0, 1, 0],
                    [0, 0, 1],
                    [0, 0, 0]])
simplex = np.array([[1, 0],
                    [0, 1],
                    [0, 0]])

In [10]:
X = np.array([[1, 1, 1, 1],
                    [2, 2, 2, 2],
                    [3, 3, 3, 3],
                    [4, 4, 4, 4],
                    [5, 5, 5, 5],
                    [6, 6, 6, 6],
                    [7, 7, 7, 7],
                    [8, 8, 8, 8]], dtype=float)
n_neighbors = 5

In [20]:
vertex_weights = np.array([1.0, 1.0, 0.5, 1.0, 1.0, 0.5, 0.5, 1.0])

In [15]:
simplices = np.array([[0, 1, 2, 3, 4],
                        [5, 2, 1, 3, 4]])

In [79]:
def reweight_simplex_vertices(X, simplices, X_vertices=None, vertex_weights=None):
    if X_vertices is None:
        X_vertices = X

    vertex_weights_simplices = vertex_weights[simplices[:,1:]]

    X_base = X[simplices[:,0]]
    X_neighbors = X_vertices[simplices[:,1:]]

    diff_vectors = X_neighbors - X_base[:,None]

    weighted = (diff_vectors.T*vertex_weights_simplices.T).T

    reverted = weighted + X_base[:,None]

    return np.concatenate([X_base[:,None], reverted], axis=1)

In [72]:
X = np.array([[1.0, 0.0],
                [2.0, 1.0],
                [3.0, 2.0]])
X_vertices = np.array([[10.0, 0.0],
                        [20.0, 10.0],
                        [30.0, 20.0]])
simplices = np.array([[0, 1]])
vertex_weights = np.array([1.0, 0.5])

In [78]:
vertex_weights_simplices = vertex_weights[simplices[:,1:]]

X_base = X[simplices[:,0]]
X_neighbors = X_vertices[simplices[:,1:]]

diff_vectors = X_neighbors[:,:,:] - X_base[:,None]

weighted = (diff_vectors.T*vertex_weights_simplices.T).T

reverted = weighted + X_base[:,None]

np.concatenate([X_base[:,None], reverted], axis=1)

array([[[ 1. ,  0. ],
        [10.5,  5. ]]])

In [77]:
diff_vectors

array([], shape=(1, 0, 2), dtype=float64)

In [81]:
reweight_simplex_vertices(X, simplices, X_vertices, vertex_weights)

array([[[ 1. ,  0. ],
        [10.5,  5. ]]])

In [16]:
X_simp = X[simplices]

In [21]:
X_base = X_simp[:,0,:]

In [32]:
vertex_weights_simp = vertex_weights[simplices[:,1:]]

In [28]:
diff_vectors = X_simp[:,1:,:] - X_base[:,None]

In [45]:
weighted = (diff_vectors.T*vertex_weights_simp.T).T

In [61]:
reverted = weighted + X_base[:,None]

In [62]:
np.concatenate([X_base[:,None], reverted], axis=1)

array([[[1. , 1. , 1. , 1. ],
        [2. , 2. , 2. , 2. ],
        [2. , 2. , 2. , 2. ],
        [4. , 4. , 4. , 4. ],
        [5. , 5. , 5. , 5. ]],

       [[6. , 6. , 6. , 6. ],
        [4.5, 4.5, 4.5, 4.5],
        [2. , 2. , 2. , 2. ],
        [4. , 4. , 4. , 4. ],
        [5. , 5. , 5. , 5. ]]])

In [38]:
diff_vectors*vertex_weights_simp[:,None]

ValueError: operands could not be broadcast together with shapes (2,4,4) (4,1,2) 

In [5]:
SMOTE().sample(X, np.array([0, 0, 0, 1, 1, 0, 1, 0]))

2022-07-20 15:33:13,099:INFO:{SMOTE}: Running sampling via {('SMOTE', "{'proportion': 1.0, 'n_neighbors': 5, 'nn_params': {}, 'n_jobs': 1, 'sampling_params': {'n_dim': 2, 'simplex_sampling': 'uniform', 'within_simplex_sampling': 'random'}, 'random_state': None}")}
2022-07-20 15:33:13,108:INFO:NearestNeighborsWithMetricTensor: NN fitting with metric minkowski
2022-07-20 15:33:13,130:INFO:NearestNeighborsWithMetricTensor: kneighbors query minkowski


(array([[1.        , 1.        , 1.        , 1.        ],
        [2.        , 2.        , 2.        , 2.        ],
        [3.        , 3.        , 3.        , 3.        ],
        [4.        , 4.        , 4.        , 4.        ],
        [5.        , 5.        , 5.        , 5.        ],
        [6.        , 6.        , 6.        , 6.        ],
        [7.        , 7.        , 7.        , 7.        ],
        [8.        , 8.        , 8.        , 8.        ],
        [6.52314702, 6.52314702, 6.52314702, 6.52314702],
        [4.54549651, 4.54549651, 4.54549651, 4.54549651]]),
 array([0, 0, 0, 1, 1, 0, 1, 0, 1, 1]))

In [6]:
dim = 3

In [7]:
dist, ind = NearestNeighbors(n_neighbors=n_neighbors).fit(X).kneighbors(X, return_distance=True)

In [8]:
ssm = SimplexSamplingMixin(n_dim=2)

In [9]:
ssm.sample_simplex(X, distances=dist, indices=ind, n_to_sample=10)

TypeError: SimplexSamplingMixin.sample_simplex() got an unexpected keyword argument 'distances'

In [ ]:
all_simplices = all_neighbor_simplices_real_idx(dim, ind)

In [ ]:
X[all_simplices][0]

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [ ]:
X2 = np.array([[[0.0, 1.0, 0.0],
                [1.0, 0.0, 0.0]],
                [[0.0, 2.0, 0.0],
                [2.0, 0.0, 0.0]]])

In [ ]:
np.sqrt(np.sum((X2[:,0,:] - X2[:,1,:])**2, axis=1))

array([1.41421356, 2.82842712])

In [ ]:
[simplex_volume(x) for x in X2]

[1.4142135623730951, 2.82842712474619]

In [ ]:
simplex_volume(X[all_simplices][1])

0.0

In [ ]:
print(neighbors_indices[:10])

NameError: name 'neighbors_indices' is not defined

In [ ]:
print(all_simplices[:10])

[[0 1 2]
 [0 1 3]
 [0 1 4]
 [0 2 3]
 [0 2 4]
 [0 3 4]
 [1 1 2]
 [1 1 3]
 [1 1 4]
 [1 2 3]]


In [ ]:
help(np.take)

Help on function take in module numpy:

take(a, indices, axis=None, out=None, mode='raise')
    Take elements from an array along an axis.
    
    When axis is not None, this function does the same thing as "fancy"
    indexing (indexing arrays using arrays); however, it can be easier to use
    if you need elements along a given axis. A call such as
    ``np.take(arr, indices, axis=3)`` is equivalent to
    ``arr[:,:,:,indices,...]``.
    
    Explained without fancy indexing, this is equivalent to the following use
    of `ndindex`, which sets each of ``ii``, ``jj``, and ``kk`` to a tuple of
    indices::
    
        Ni, Nk = a.shape[:axis], a.shape[axis+1:]
        Nj = indices.shape
        for ii in ndindex(Ni):
            for jj in ndindex(Nj):
                for kk in ndindex(Nk):
                    out[ii + jj + kk] = a[ii + (indices[jj],) + kk]
    
    Parameters
    ----------
    a : array_like (Ni..., M, Nk...)
        The source array.
    indices : array_like (Nj...

In [ ]:
np.take(neighbors_indices[:10], all_simplices[:10])

array([[0, 1, 2],
       [0, 1, 3],
       [0, 1, 4],
       [0, 2, 3],
       [0, 2, 4],
       [0, 3, 4],
       [1, 1, 2],
       [1, 1, 3],
       [1, 1, 4],
       [1, 2, 3]])

In [ ]:
arr[:,idx]

array([[[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]],

       [[3, 4, 5],
        [3, 4, 5],
        [3, 4, 5]],

       [[6, 7, 8],
        [6, 7, 8],
        [6, 7, 8]]])

In [ ]:
def array_array_index(array, indices):
    """
    Take samples from an array by indices row by row

    Args:
        array (np.array): array to sample from
        indices (np.array): array of indices
    
    Returns:
        array (indices.shape): the sampled values
    """
    stride = np.arange(indices.shape[0])*array.shape[1]
    indices_mod = indices + stride[:, None]
    indices_flat = indices_mod.flatten()
    return array.flatten()[indices_flat].reshape(indices.shape)
    

In [ ]:
arr = np.array([[0, 1, 2, 3], [3, 4, 5, 6], [6, 7, 8, 9], [10, 11, 12, 13]])
idx = np.array([[0, 1, 3], [0, 2, 3], [3, 1, 2], [0, 0, 0]])
np.take(arr, idx)

array([[0, 1, 3],
       [0, 2, 3],
       [3, 1, 2],
       [0, 0, 0]])

In [ ]:
array_array_index(arr, idx)

array([[ 0,  1,  3],
       [ 3,  5,  6],
       [ 9,  7,  8],
       [10, 10, 10]])

In [ ]:
arr.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.arange(idx.shape[0])*arr.shape[1]

array([0, 3, 6])

In [ ]:
idx_mod = idx + (np.arange(idx.shape[0])*arr.shape[1])[:, None]

In [ ]:
idx_mod

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
idx_mod.reshape(np.prod(idx_mod.shape))

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
arr.reshape(np.prod(arr.shape))[idx_mod].reshape(arr.shape)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr[:,:][idx]

IndexError: index 1 is out of bounds for axis 0 with size 1

In [ ]:
neighbor_vector_indices = np.take(neighbors_indices, all_simplices[:,1:])

In [ ]:
len(all_simplices)

42

In [ ]:
len(neighbor_vector_indices)

42

In [ ]:
neighbor_vector_indices

array([[1, 2],
       [1, 3],
       [1, 4],
       [2, 3],
       [2, 4],
       [3, 4],
       [1, 2],
       [1, 3],
       [1, 4],
       [2, 3],
       [2, 4],
       [3, 4],
       [1, 2],
       [1, 3],
       [1, 4],
       [2, 3],
       [2, 4],
       [3, 4],
       [1, 2],
       [1, 3],
       [1, 4],
       [2, 3],
       [2, 4],
       [3, 4],
       [1, 2],
       [1, 3],
       [1, 4],
       [2, 3],
       [2, 4],
       [3, 4],
       [1, 2],
       [1, 3],
       [1, 4],
       [2, 3],
       [2, 4],
       [3, 4],
       [1, 2],
       [1, 3],
       [1, 4],
       [2, 3],
       [2, 4],
       [3, 4]])

In [ ]:
simplex_indices = np.vstack([base_vector_indices.T, neighbor_vector_indices.T]).T

In [ ]:
simplex_indices

array([[0, 1, 2],
       [0, 1, 3],
       [0, 1, 4],
       [0, 2, 3],
       [0, 2, 4],
       [0, 3, 4],
       [1, 1, 2],
       [1, 1, 3],
       [1, 1, 4],
       [1, 2, 3],
       [1, 2, 4],
       [1, 3, 4],
       [2, 1, 2],
       [2, 1, 3],
       [2, 1, 4],
       [2, 2, 3],
       [2, 2, 4],
       [2, 3, 4],
       [3, 1, 2],
       [3, 1, 3],
       [3, 1, 4],
       [3, 2, 3],
       [3, 2, 4],
       [3, 3, 4],
       [4, 1, 2],
       [4, 1, 3],
       [4, 1, 4],
       [4, 2, 3],
       [4, 2, 4],
       [4, 3, 4],
       [5, 1, 2],
       [5, 1, 3],
       [5, 1, 4],
       [5, 2, 3],
       [5, 2, 4],
       [5, 3, 4],
       [6, 1, 2],
       [6, 1, 3],
       [6, 1, 4],
       [6, 2, 3],
       [6, 2, 4],
       [6, 3, 4]])

In [ ]:




simplex_indices = np.vstack([base_vector_indices.T, neighbor_vector_indices.T]).T

In [ ]:
simplex_indices

array([[0, 1, 2, 0, 1],
       [0, 1, 2, 0, 1],
       [0, 1, 2, 0, 1],
       [0, 1, 2, 0, 1],
       [0, 1, 2, 0, 1],
       [0, 1, 2, 0, 1],
       [0, 1, 2, 0, 1],
       [0, 1, 2, 0, 1],
       [0, 1, 2, 0, 1],
       [0, 1, 2, 0, 1],
       [0, 1, 2, 0, 1],
       [0, 1, 2, 0, 1],
       [1, 0, 2, 0, 1],
       [1, 0, 2, 0, 1],
       [1, 0, 2, 0, 1],
       [1, 0, 2, 0, 1],
       [1, 0, 2, 0, 1],
       [1, 0, 2, 0, 1],
       [1, 0, 2, 0, 1],
       [1, 0, 2, 0, 1],
       [1, 0, 2, 0, 1],
       [1, 0, 2, 0, 1],
       [1, 0, 2, 0, 1],
       [1, 0, 2, 0, 1],
       [2, 1, 0, 1, 0],
       [2, 1, 0, 1, 0],
       [2, 1, 0, 1, 0],
       [2, 1, 0, 1, 0],
       [2, 1, 0, 1, 0],
       [2, 1, 0, 1, 0],
       [2, 1, 0, 1, 0],
       [2, 1, 0, 1, 0],
       [2, 1, 0, 1, 0],
       [2, 1, 0, 1, 0],
       [2, 1, 0, 1, 0],
       [2, 1, 0, 1, 0],
       [3, 2, 1, 3, 1],
       [3, 2, 1, 3, 1],
       [3, 2, 1, 3, 1],
       [3, 2, 1, 3, 1],
       [3, 2, 1, 3, 1],
       [3, 2, 1,

In [ ]:
picked = all_simplices[np.random.choice(np.arange(all_simplices.shape[0]), 10)]

In [ ]:
weights = np.ones(simplices.shape)

In [ ]:
weights = weights/np.sum(weights, axis=1)[:, None]

In [ ]:
picked

array([[5, 1, 1],
       [1, 2, 2],
       [1, 2, 4],
       [0, 2, 1],
       [3, 1, 4],
       [1, 3, 2],
       [1, 3, 3],
       [3, 2, 4],
       [0, 4, 3],
       [2, 2, 2]])

In [ ]:
ind[picked[:,0]]

array([[5, 6, 4, 3, 2],
       [1, 0, 2, 3, 4],
       [1, 0, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [3, 2, 4, 5, 1],
       [1, 0, 2, 3, 4],
       [1, 0, 2, 3, 4],
       [3, 2, 4, 5, 1],
       [0, 1, 2, 3, 4],
       [2, 1, 3, 4, 0]])

In [ ]:
picked[:,1:]

array([[1, 1],
       [2, 2],
       [2, 4],
       [2, 1],
       [1, 4],
       [3, 2],
       [3, 3],
       [2, 4],
       [4, 3],
       [2, 2]])

In [ ]:
bases = ind[picked[:,0]]

In [ ]:
bases

array([[5, 6, 4, 3, 2],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [3, 2, 4, 5, 1],
       [6, 5, 4, 3, 2],
       [0, 1, 2, 3, 4],
       [4, 5, 3, 6, 2],
       [6, 5, 4, 3, 2],
       [6, 5, 4, 3, 2]])

In [ ]:
np.take(bases, picked[:,1:])

array([[6, 6],
       [4, 4],
       [4, 2],
       [4, 6],
       [6, 2],
       [3, 4],
       [3, 3],
       [4, 2],
       [2, 3],
       [4, 4]])

In [ ]:
simplices_final = np.vstack([picked[:,0].T, np.take(bases, picked[:,1:]).T]).T

In [ ]:
X[simplices_final]

array([[[6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.]],

       [[2., 2., 2., 2.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]],

       [[2., 2., 2., 2.],
        [5., 5., 5., 5.],
        [3., 3., 3., 3.]],

       [[1., 1., 1., 1.],
        [5., 5., 5., 5.],
        [7., 7., 7., 7.]],

       [[4., 4., 4., 4.],
        [7., 7., 7., 7.],
        [3., 3., 3., 3.]],

       [[2., 2., 2., 2.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.]],

       [[2., 2., 2., 2.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]],

       [[4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [3., 3., 3., 3.]],

       [[1., 1., 1., 1.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.]],

       [[3., 3., 3., 3.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]]])

In [ ]:
bases[picked[:,1:]]

array([[[[0, 1, 2, 3, 4]],

        [[0, 1, 2, 3, 4]],

        [[0, 1, 2, 3, 4]]],


       [[[0, 1, 2, 3, 4]],

        [[0, 1, 2, 3, 4]],

        [[0, 1, 2, 3, 4]]],


       [[[0, 1, 2, 3, 4]],

        [[3, 2, 4, 5, 1]],

        [[0, 1, 2, 3, 4]]],


       [[[0, 1, 2, 3, 4]],

        [[0, 1, 2, 3, 4]],

        [[0, 1, 2, 3, 4]]],


       [[[0, 1, 2, 3, 4]],

        [[0, 1, 2, 3, 4]],

        [[0, 1, 2, 3, 4]]],


       [[[0, 1, 2, 3, 4]],

        [[3, 2, 4, 5, 1]],

        [[3, 2, 4, 5, 1]]],


       [[[0, 1, 2, 3, 4]],

        [[0, 1, 2, 3, 4]],

        [[0, 1, 2, 3, 4]]],


       [[[0, 1, 2, 3, 4]],

        [[3, 2, 4, 5, 1]],

        [[0, 1, 2, 3, 4]]],


       [[[0, 1, 2, 3, 4]],

        [[0, 1, 2, 3, 4]],

        [[0, 1, 2, 3, 4]]],


       [[[0, 1, 2, 3, 4]],

        [[0, 1, 2, 3, 4]],

        [[0, 1, 2, 3, 4]]]])

In [ ]:
simplex_neighbor

array([[[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]],

       [[0, 1, 2, 3, 4],
        [3, 2, 4, 5, 1],
        [0, 1, 2, 3, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]],

       [[0, 1, 2, 3, 4],
        [3, 2, 4, 5, 1],
        [3, 2, 4, 5, 1]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]],

       [[0, 1, 2, 3, 4],
        [3, 2, 4, 5, 1],
        [0, 1, 2, 3, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [ ]:
weighted_simplices = X[ind]

In [ ]:
simplices = np.array([[0, 1, 2],
                    [0, 1, 3]])

In [ ]:
weights = np.random.rand(*simplices.shape)
weights = np.ones(simplices.shape)

In [ ]:
weights = weights/np.sum(weights, axis=1)[:, None]

In [ ]:
weights

array([[0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333]])

In [ ]:
X[simplices]

array([[[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]],

       [[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [4., 4., 4., 4.]]])

In [ ]:
weighted_simplices = X[simplices]*weights[:, :, None]

In [ ]:
weighted_simplices

array([[[0.33333333, 0.33333333, 0.33333333, 0.33333333],
        [0.66666667, 0.66666667, 0.66666667, 0.66666667],
        [1.        , 1.        , 1.        , 1.        ]],

       [[0.33333333, 0.33333333, 0.33333333, 0.33333333],
        [0.66666667, 0.66666667, 0.66666667, 0.66666667],
        [1.33333333, 1.33333333, 1.33333333, 1.33333333]]])

In [ ]:
np.sum(weighted_simplices, axis=1)

array([[2.        , 2.        , 2.        , 2.        ],
       [2.33333333, 2.33333333, 2.33333333, 2.33333333]])

In [ ]:
from smote_variants import SimplexSamplingMixin

In [ ]:
ssm = SimplexSamplingMixin(n_dim=2, simplex_sampling='uniform', within_simplex_sampling='random', random_state=5)

In [ ]:
ssm.get_params()

{'sampling_params': {'n_dim': 2,
  'simplex_sampling': 'uniform',
  'within_simplex_sampling': 'random'},
 'random_state': 5}

In [ ]:
from sklearn.neighbors import NearestNeighbors

In [ ]:
nn = NearestNeighbors(n_neighbors=3).fit(X)
dist, ind = nn.kneighbors(X, return_distance=True)

In [ ]:
ssm.sample_simplex(X, distances=dist, indices=ind, n_to_sample=3)

ValueError: operands could not be broadcast together with shapes (2,3,3,4) (3,2,1) 

In [ ]:
simplices

array([[0, 1, 2],
       [0, 1, 3]])

In [ ]:
ind[(simplices.T)]

array([[[0, 1, 2],
        [0, 1, 2]],

       [[1, 2, 0],
        [1, 2, 0]],

       [[2, 1, 3],
        [3, 4, 2]]])

In [ ]:
X[ind[np.arange(len(simplices)), simplices]]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (2,3) 