In [23]:
import numpy as np

a= np.array([[2, 1], [1, 1.5]])
b= np.array([[3, 2], [2, 2.0]])
c= np.array([[3, 1], [1, 0.5]])

In [24]:
np.linalg.det(a), np.linalg.det(b), np.linalg.det(c)

(2.0, 2.0000000000000004, 0.5000000000000001)

In [25]:
def psd_mean(matrices):
    dets= [np.linalg.det(m) for m in matrices]
    desired_det= np.prod(dets)**(1.0/len(dets))

    result= np.mean(matrices, axis=0)

    result= result/np.linalg.det(result)**(1.0/len(matrices[0][0]))
    result= result*desired_det**(1.0/len(matrices[0][0]))

    return result

In [26]:
res= psd_mean([a, b, c])

In [27]:
np.linalg.det(res)

1.2599210498948732

In [28]:
res

array([[2.2449241 , 1.12246205],
       [1.12246205, 1.12246205]])

In [36]:
x= np.random.rand(10)

In [40]:
from scipy.stats import rankdata

In [37]:
x

array([0.5042964 , 0.56219006, 0.49862953, 0.57563737, 0.53526203,
       0.8625502 , 0.18874556, 0.21490319, 0.38637931, 0.74324377])

In [41]:
rankdata(x)

array([ 5.,  7.,  4.,  8.,  6., 10.,  1.,  2.,  3.,  9.])

In [44]:
x[np.argsort(x)[len(x) - rankdata(x).astype(int)]]

array([0.53526203, 0.49862953, 0.56219006, 0.38637931, 0.5042964 ,
       0.18874556, 0.8625502 , 0.74324377, 0.57563737, 0.21490319])

In [39]:
np.argsort(x)

array([6, 7, 8, 2, 0, 4, 1, 3, 9, 5])

In [38]:
x[len(x) - np.argsort(x) - 1]

array([0.57563737, 0.49862953, 0.56219006, 0.21490319, 0.74324377,
       0.8625502 , 0.38637931, 0.18874556, 0.5042964 , 0.53526203])